name: bloc_devtools_example
description: Example counter app demonstrating bloc_devtools_extension usage.

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.0
  bloc: ^8.1.0
  bloc_devtools_extension:
    path: ../

flutter:
  uses-material-design: true
